# gateway-service-local.yml
spring:
  config:
    activate:
      on-profile: local

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

jwt:
  secret-key: kyo
  expires-minutes: 1440 # 24hr
---
# gateway-service-dev.yml
spring:
  config:
    activate:
      on-profile: dev

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

jwt:
  secret-key: my_token
  expires-minutes: 1440 # 24hr
